version: '2.23.0-desktop.1'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kareits/fin_scoring
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  gateway:
    image: kareits/gateway
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend
    ports:
      - 8000:80